### ISSUE TITLE
Sar human readable format is not part of this repo /bernhardk/py2to3-wip-1 and t_bernhardk/2to3-10-2to3-fix-filter+1.

### ISSUE THREAD

**Issue by ashwin9390** [xenserver/status-report#16]
During code review  ,i do not see XSI-1385 included in the commit ,It should be included in the latest commit.

**Comment by ashwin9390** [comment]
All the files and directories are generated correctly when performing test on file , directory  generation ,writing to the file and providing the location of the bugreport. 

Test case included following scenario,

1.Invoking xenbugtool with user input for each Include file/directory option ,no errors seen .
2.Output file is written to correct location and provides the status of the run along with format of the file .
3.Checking for files and it's content -condition(not empty) and has valid message and right files .

**Comment by bernhardkaindl** [comment]
Thanks, these branches were only early prototyping. It missing the sar fixes is fine.

They are now obsoleted by PR https://github.com/xenserver/status-report/pull/33.
